### ISSUE TITLE
Idea: Missing read permissions must not be pop up

### ISSUE THREAD

**Issue by ttofis** [synac-chat/client-gtk#2]
It better be a bold red centered text on the top of the chat log saying that you are missign the permissions rather than a pop up box. Thanks!

**Comment by jD91mZM2** [comment]
But what if you're scrolled all the way down (because you had permissions, but you lost them)? Then you won't see it!

**Comment by ttofis** [comment]
Ok, an error box? A utf warning sign with hover text saying it (also in red)? That text but on bottom and in a red box? IDK but pls no pop up window.
